app_financiera/urls.py
from django.urls import path
from . import views

app_name = 'financiera'

urlpatterns = [
    path('', views.index, name='index'),
    path('deposito/', views.deposito, name="deposito"),
    path('retiro/', views.retiro, name="retiro"),
]

empresa_financiera/urls.py
from os import name
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app_seguridad import views   

urlpatterns = [
    path('admin/', admin.site.urls),
    path('financiera/', include('app_financiera.urls')),
    path('', views.index),
    path('login/', views.log_in, name="login_view"),
    path('logout/', views.log_out, name="logout_view"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_financiera/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.db.models.fields.related import ForeignKey

# Create your models here.
class Cliente(models.Model):
    nombre = models.CharField(max_length=30)
    apellido = models.CharField(max_length=30)
    direccion = models.CharField(max_length=30)
    fecha_nacimiento = models.DateField()
    telefono = models.IntegerField()
    correo = models.EmailField(null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return self.nombre

class Cuenta_Bancaria(models.Model):
    ESTADOS= (
        ('1', 'Activa'),
        ('2', 'Inactiva'),
    )
    fecha_creacion = models.DateField()
    estado = models.CharField(max_length=1, choices=ESTADOS, default='1')
    saldo = models.DecimalField(max_digits=12, decimal_places=4)
    propietario = models.OneToOneField(Cliente, on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return f'{self.saldo}'

class Depositar(models.Model):

    monto = models.DecimalField(max_digits=12, decimal_places=4)
    fecha = models.DateTimeField(auto_now=True)
    cuenta = models.ForeignKey(Cuenta_Bancaria, on_delete=models.CASCADE)

app_seguridad/models.py
from django.db import models

# Create your models here.

app_financiera/views.py
from app_financiera.models import Cliente, Cuenta_Bancaria, Depositar
from django import http
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from decimal import Decimal


# Create your views here.

@login_required()
def index(request):
     return render(request, 'financiera/index.html')

@login_required()
def deposito(request):
     
     if request.method == 'POST':
        dep = Cuenta_Bancaria.objects.get(pk=request.user.cliente.cuenta_bancaria.pk)
        monto = Decimal(request.POST.get('monto'))
        deposito = Depositar(monto=monto, cuenta=dep)
        deposito.save()
        cuenta = Cuenta_Bancaria.objects.filter(pk=request.user.cliente.cuenta_bancaria.pk).first()
        cuenta.saldo= cuenta.saldo + monto
        cuenta.save()      
        return redirect('/')

     return render(request, 'financiera/deposito.html')
  
@login_required()
def retiro(request):
     
     if request.method == 'POST':
        dep = Cuenta_Bancaria.objects.get(pk=request.user.cliente.cuenta_bancaria.pk)
        monto = Decimal(request.POST.get('monto'))
        deposito = Depositar(monto=monto, cuenta=dep)
        deposito.save()
        cuenta = Cuenta_Bancaria.objects.filter(pk=request.user.cliente.cuenta_bancaria.pk).first()
        cuenta.saldo= cuenta.saldo - monto
        cuenta.save()      
        return redirect('/')

     return render(request, 'financiera/retiro.html')

app_seguridad/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return redirect(reverse('financiera:index'))

        
    return render(request, 'seguridad/index.html')

def log_in(request):
    if request.method == 'POST':
        username = request.POST.get('usuario')
        password = request.POST.get('contrasena')

        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(reverse('financiera:index'))
        else:
            messages.add_message(request, messages.ERROR, 'El usuario o contraseña son incorrectos o su cuenta ha sido desactivada')
            return redirect('/')

        return HttpResponse(f'Usuario: {user} - Clave: {pawd}')
    else:
        return redirect('/')


def log_out(request):
    logout(request)
    return redirect('/')

app_financiera/templates/financiera/deposito.html
{% extends "base.html" %}

{% block title %}
    Deposito
{% endblock %}

{% block container%}
    <h1>Realizar un Deposito</h1>
    
    <form  action="{% url 'financiera:deposito' %}" method="post">
        {% csrf_token %}
        <div class="mb-1">
            <label  for="exampleFormControlInput1" class="form-label">Monto a depositar:</label>
            <input name="monto" type="text" class="form-control" id="exampleFormControlInput1" placeholder="1000" required >
        </div>
        <div class="col-auto">
            <input type="submit" class="btn btn-success" value="Confirmar"/>
        </div>
    </form>
    
{% endblock %}

app_financiera/templates/financiera/index.html
{% extends "base.html" %}

{% block title %}
    Inicio
{% endblock %}

{% block container%}
    <h1>Bienvenido a la app de finanzas</h1>        
      
{% endblock %}

app_financiera/templates/financiera/retiro.html
{% extends "base.html" %}

{% block title %}
    Retiro
{% endblock %}

{% block container%}
    <h1>Realizar un Retiro</h1>
    
    <form action="{% url 'financiera:retiro %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            
            <label for="exampleFormControlInput1" class="form-label">Monto a retirar</label>
            <input name="monto" type="text" class="form-control" id="exampleFormControlInput1" placeholder="1000" required >
        </div>
        <div class="col-auto">
            <input type="submit" class="btn btn-success" value="Confirmar Deposito"/>
        </div>
    </form>
    
{% endblock %}

app_seguridad/templates/seguridad/index.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
        <meta name="generator" content="Hugo 0.84.0">
        <title>Login</title>

        <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">

        <!-- Bootstrap core CSS -->
        <link href="{% static 'financiera/bootstrap/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
        <link href="{% static 'financiera/css/signin.css' %}" rel="stylesheet">

        <!-- Favicons -->
        
        <meta name="theme-color" content="#7952b3">

        <style>
            .bd-placeholder-img {
                font-size: 1.125rem;
                text-anchor: middle;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
            }

            #login-error {
                position: absolute;
                top: 0;
                width: 100%;
            }

            @media (min-width: 768px) {
                .bd-placeholder-img-lg {
                    font-size: 3.5rem;
                }
            }
        </style>       
    </head>

    <body class="text-center">
        {% if messages %}
            {% for message in messages %}
                <div id="login-error" class="alert alert-danger">{{ message }}</div>
            {% endfor %}
        {% endif %}


        <main class="form-signin">
            <form action="{% url 'login_view' %}" method="post">
                {% csrf_token %}
                <h1 class="h3 mb-3 fw-normal">Iniciar Sesion</h1>

                <div class="form-floating">
                    <input autofocus name="usuario" type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Usuario</label>
                </div>

                <div class="form-floating">
                    <input name="contrasena" type="password" class="form-control" id="floatingPassword" placeholder="Password">
                    <label for="floatingPassword">Contraseña</label>
                </div>

                <button class="w-100 btn btn-lg btn-primary" type="submit">Iniciar sesión</button>
                <p class="mt-5 mb-3 text-muted">Flaxtac&copy; 2021-2022</p>
            </form>
        </main>
    </body>
</html>